#! /bin/sh

# Autorun
sxhkd &
$HOME/.config/polybar/launch.sh &
feh --bg-fill ~/Pictures/wallpaper/737474.png
pcloudcc -u limbardi@protonmail.com -d &
/opt/xdman/jre/bin/java -Xmx1024m -jar /opt/xdman/xdman.jar -m &
xautolock -time 30 -locker "betterlockscreen -l dimblur -t 'locked bruh'" -corners 0++0 &

picom -f -i 0.9 &

bspc monitor -d term www work media game

bspc config border_width        3
bspc config window_gap          7

bspc config normal_border_color "#44475a"
bspc config active_border_color "#bd93f9"
bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config split_ratio				0.50
bspc config borderless_monocle		true
bspc config gapless_monocle			true
bspc config top_padding				-8
bspc config bottom_padding			0

bspc rule -a feh state=tiled follow=on
bspc rule -a "/opt/xdman/xdman" state=floating
bspc rule -a Lxappearance state=floating follow=on
bspc rule -a Bitwarden state=floating follow=on
bspc rule -a "steam-runtime %U" desktop='^5'
bspc rule -a discord desktop='^5'
bspc rule -a spotify desktop='^4'

# Touchpad Setting
xinput set-prop "Elan Touchpad" "libinput Tapping Enabled" 1
xinput set-prop "Elan Touchpad" "libinput Natural Scrolling Enabled" 1
